EJemplo sobre IRIS, (datos sobre un tipo de flor)

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("data/iris.data.csv")
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

Mostramos las últimas filas

In [3]:
df.tail()

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

En este caso no hay cabacera (header), Podemos establecer columnas para el DATAFRAME

In [4]:
df.columns= ["long_sepalo", "ancho_sepalo", "long_petalo", "ancho_petalo", "clase"]
df

     long_sepalo  ancho_sepalo  long_petalo  ancho_petalo           clase
0            4.9           3.0          1.4           0.2     Iris-setosa
1            4.7           3.2          1.3           0.2     Iris-setosa
2            4.6           3.1          1.5           0.2     Iris-setosa
3            5.0           3.6          1.4           0.2     Iris-setosa
4            5.4           3.9          1.7           0.4     Iris-setosa
..           ...           ...          ...           ...             ...
144          6.7           3.0          5.2           2.3  Iris-virginica
145          6.3           2.5          5.0           1.9  Iris-virginica
146          6.5           3.0          5.2           2.0  Iris-virginica
147          6.2           3.4          5.4           2.3  Iris-virginica
148          5.9           3.0          5.1           1.8  Iris-virginica

[149 rows x 5 columns]

In [5]:
df.describe()

       long_sepalo  ancho_sepalo  long_petalo  ancho_petalo
count   149.000000    149.000000   149.000000    149.000000
mean      5.848322      3.051007     3.774497      1.205369
std       0.828594      0.433499     1.759651      0.761292
min       4.300000      2.000000     1.000000      0.100000
25%       5.100000      2.800000     1.600000      0.300000
50%       5.800000      3.000000     4.400000      1.300000
75%       6.400000      3.300000     5.100000      1.800000
max       7.900000      4.400000     6.900000      2.500000

Podemos contar valores en una columna

In [6]:
df["clase"].value_counts()

clase
Iris-versicolor    50
Iris-virginica     50
Iris-setosa        49
Name: count, dtype: int64

Ordenar datos ascendente o descendente

In [7]:
#df.sort_values('ancho_sepalo')
df.sort_values('ancho_sepalo', ascending=False)

     long_sepalo  ancho_sepalo  long_petalo  ancho_petalo            clase
14           5.7           4.4          1.5           0.4      Iris-setosa
32           5.5           4.2          1.4           0.2      Iris-setosa
31           5.2           4.1          1.5           0.1      Iris-setosa
13           5.8           4.0          1.2           0.2      Iris-setosa
4            5.4           3.9          1.7           0.4      Iris-setosa
..           ...           ...          ...           ...              ...
52           5.5           2.3          4.0           1.3  Iris-versicolor
67           6.2           2.2          4.5           1.5  Iris-versicolor
61           6.0           2.2          4.0           1.0  Iris-versicolor
118          6.0           2.2          5.0           1.5   Iris-virginica
59           5.0           2.0          3.5           1.0  Iris-versicolor

[149 rows x 5 columns]

Podemos cambiar filas por columnas

In [8]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,139,140,141,142,143,144,145,146,147,148
long_sepalo,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,5.4,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
ancho_sepalo,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,3.7,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
long_petalo,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
ancho_petalo,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,0.2,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
clase,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

Filtrar ppor una columna

In [9]:
df[df["long_petalo"]>=5]

     long_sepalo  ancho_sepalo  long_petalo  ancho_petalo            clase
76           6.7           3.0          5.0           1.7  Iris-versicolor
82           6.0           2.7          5.1           1.6  Iris-versicolor
99           6.3           3.3          6.0           2.5   Iris-virginica
100          5.8           2.7          5.1           1.9   Iris-virginica
101          7.1           3.0          5.9           2.1   Iris-virginica
102          6.3           2.9          5.6           1.8   Iris-virginica
103          6.5           3.0          5.8           2.2   Iris-virginica
104          7.6           3.0          6.6           2.1   Iris-virginica
106          7.3           2.9          6.3           1.8   Iris-virginica
107          6.7           2.5          5.8           1.8   Iris-virginica
108          7.2           3.6          6.1           2.5   Iris-virginica
109          6.5           3.2          5.1           2.0   Iris-virginica
110          6.4           2.7          5.3           1.9   Iris-virginica
111          6.8           3.0          5.5           2.1   Iris-virginica
112          5.7           2.5          5.0           2.0   Iris-virginica
113          5.8           2.8          5.1           2.4   Iris-virginica
114          6.4           3.2          5.3           2.3   Iris-virginica
115          6.5           3.0          5.5           1.8   Iris-virginica
116          7.7           3.8          6.7           2.2   Iris-virginica
117          7.7           2.6          6.9           2.3   Iris-virginica
118          6.0           2.2          5.0           1.5   Iris-virginica
119          6.9           3.2          5.7           2.3   Iris-virginica
121          7.7           2.8          6.7           2.0   Iris-virginica
123          6.7           3.3          5.7           2.1   Iris-virginica
124          7.2           3.2          6.0           1.8   Iris-virginica
127          6.4           2.8          5.6           2.1   Iris-virginica
128          7.2           3.0          5.8           1.6   Iris-virginica
129          7.4           2.8          6.1           1.9   Iris-virginica
130          7.9           3.8          6.4           2.0   Iris-virginica
131          6.4           2.8          5.6           2.2   Iris-virginica
132          6.3           2.8          5.1           1.5   Iris-virginica
133          6.1           2.6          5.6           1.4   Iris-virginica
134          7.7           3.0          6.1           2.3   Iris-virginica
135          6.3           3.4          5.6           2.4   Iris-virginica
136          6.4           3.1          5.5           1.8   Iris-virginica
138          6.9           3.1          5.4           2.1   Iris-virginica
139          6.7           3.1          5.6           2.4   Iris-virginica
140          6.9           3.1          5.1           2.3   Iris-virginica
141          5.8           2.7          5.1           1.9   Iris-virginica
142          6.8           3.2          5.9           2.3   Iris-virginica
143          6.7           3.3          5.7           2.5   Iris-virginica
144          6.7           3.0          5.2           2.3   Iris-virginica
145          6.3           2.5          5.0           1.9   Iris-virginica
146          6.5           3.0          5.2           2.0   Iris-virginica
147          6.2           3.4          5.4           2.3   Iris-virginica
148          5.9           3.0          5.1           1.8   Iris-virginica

Filtrar por mas de una condición.
Se utiliza & para AND 
Se utiliza | para OR

In [10]:
df[
    (df["long_petalo"]>=5)
    &
    (df["ancho_petalo"]>=1.5)
    ]

     long_sepalo  ancho_sepalo  long_petalo  ancho_petalo            clase
76           6.7           3.0          5.0           1.7  Iris-versicolor
82           6.0           2.7          5.1           1.6  Iris-versicolor
99           6.3           3.3          6.0           2.5   Iris-virginica
100          5.8           2.7          5.1           1.9   Iris-virginica
101          7.1           3.0          5.9           2.1   Iris-virginica
102          6.3           2.9          5.6           1.8   Iris-virginica
103          6.5           3.0          5.8           2.2   Iris-virginica
104          7.6           3.0          6.6           2.1   Iris-virginica
106          7.3           2.9          6.3           1.8   Iris-virginica
107          6.7           2.5          5.8           1.8   Iris-virginica
108          7.2           3.6          6.1           2.5   Iris-virginica
109          6.5           3.2          5.1           2.0   Iris-virginica
110          6.4           2.7          5.3           1.9   Iris-virginica
111          6.8           3.0          5.5           2.1   Iris-virginica
112          5.7           2.5          5.0           2.0   Iris-virginica
113          5.8           2.8          5.1           2.4   Iris-virginica
114          6.4           3.2          5.3           2.3   Iris-virginica
115          6.5           3.0          5.5           1.8   Iris-virginica
116          7.7           3.8          6.7           2.2   Iris-virginica
117          7.7           2.6          6.9           2.3   Iris-virginica
118          6.0           2.2          5.0           1.5   Iris-virginica
119          6.9           3.2          5.7           2.3   Iris-virginica
121          7.7           2.8          6.7           2.0   Iris-virginica
123          6.7           3.3          5.7           2.1   Iris-virginica
124          7.2           3.2          6.0           1.8   Iris-virginica
127          6.4           2.8          5.6           2.1   Iris-virginica
128          7.2           3.0          5.8           1.6   Iris-virginica
129          7.4           2.8          6.1           1.9   Iris-virginica
130          7.9           3.8          6.4           2.0   Iris-virginica
131          6.4           2.8          5.6           2.2   Iris-virginica
132          6.3           2.8          5.1           1.5   Iris-virginica
134          7.7           3.0          6.1           2.3   Iris-virginica
135          6.3           3.4          5.6           2.4   Iris-virginica
136          6.4           3.1          5.5           1.8   Iris-virginica
138          6.9           3.1          5.4           2.1   Iris-virginica
139          6.7           3.1          5.6           2.4   Iris-virginica
140          6.9           3.1          5.1           2.3   Iris-virginica
141          5.8           2.7          5.1           1.9   Iris-virginica
142          6.8           3.2          5.9           2.3   Iris-virginica
143          6.7           3.3          5.7           2.5   Iris-virginica
144          6.7           3.0          5.2           2.3   Iris-virginica
145          6.3           2.5          5.0           1.9   Iris-virginica
146          6.5           3.0          5.2           2.0   Iris-virginica
147          6.2           3.4          5.4           2.3   Iris-virginica
148          5.9           3.0          5.1           1.8   Iris-virginica

Comprobar valores pedidos dentro del DATAFRAME

In [11]:
df.isna().sum()

long_sepalo     0
ancho_sepalo    0
long_petalo     0
ancho_petalo    0
clase           0
dtype: int64

Vamos aponer valores NaN a alguna columna/fila

In [12]:
df['long_petalo'][:2]=np.nan
df.head()

/var/folders/4z/c52zmv8x4ls48rw7nsn3f1gm0000gq/T/ipykernel_41925/2351001754.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['long_petalo'][:2]=np.nan
/var/folders/4z/c52zmv8x4ls48rw7nsn3f1gm0000gq/T/ipykernel_41925/2351001754.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['long_petalo'][:2]=np.nan

   long_sepalo  ancho_sepalo  long_petalo  ancho_petalo        clase
0          4.9           3.0          NaN           0.2  Iris-setosa
1          4.7           3.2          NaN           0.2  Iris-setosa
2          4.6           3.1          1.5           0.2  Iris-setosa
3          5.0           3.6          1.4           0.2  Iris-setosa
4          5.4           3.9          1.7           0.4  Iris-setosa

Mostrar valores nulos

In [13]:
df.isna().sum()

long_sepalo     0
ancho_sepalo    0
long_petalo     2
ancho_petalo    0
clase           0
dtype: int64

Podemos quitar los valores si sabemos donde están con fillnan

In [14]:
df['long_petalo']=df['long_petalo'].fillna(2.9)
df.head()

   long_sepalo  ancho_sepalo  long_petalo  ancho_petalo        clase
0          4.9           3.0          2.9           0.2  Iris-setosa
1          4.7           3.2          2.9           0.2  Iris-setosa
2          4.6           3.1          1.5           0.2  Iris-setosa
3          5.0           3.6          1.4           0.2  Iris-setosa
4          5.4           3.9          1.7           0.4  Iris-setosa